# Generated by Django 5.0.1 on 2024-03-30 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 30, 4, 0, 40, 479200, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
