# Generated by Django 5.0.1 on 2024-03-30 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 3, 30, 9, 27, 51, 591269, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
    ]
