# Generated by Django 5.0.1 on 2024-04-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark', models.BooleanField(default=False, verbose_name='içerik')),
            ],
        ),
    ]
