# Generated by Django 5.0.1 on 2024-04-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mode',
        ),
    ]
