# Generated by Django 5.0.1 on 2024-04-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_delete_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
